### ISSUE TITLE
KLN90B inner knob (2D popup)

### ISSUE THREAD

**Issue by birdydma** [mixMugz/An-24#10]
They are broken
![2020-09-07_18h44_59](https://user-images.githubusercontent.com/30256581/92407545-2c7d6000-f13b-11ea-8304-f6051504fd4e.jpg)

**Comment by mixMugz** [comment]
In 2D or in 3D? If in 3D they are already fixed. In 2D i didnt see any problem. Can you take video?

**Comment by birdydma** [comment]
2D only, 3D is perfect.

**Comment by mixMugz** [comment]
> 2D only, 3D is perfect.

Can you provide video + log?

**Comment by birdydma** [comment]
Here is
[Log.txt](https://github.com/mixMugz/An-24/files/5212752/Log.txt)

[2020-09-12_15h43_40.zip](https://github.com/mixMugz/An-24/files/5212754/2020-09-12_15h43_40.zip)

**Comment by mixMugz** [comment]
> Here is
> [Log.txt](https://github.com/mixMugz/An-24/files/5212752/Log.txt)
> 
> [2020-09-12_15h43_40.zip](https://github.com/mixMugz/An-24/files/5212754/2020-09-12_15h43_40.zip)

Oh man. You are clicking. Click is used for push/pull button. Use mouse scroll for rotation.

**Comment by birdydma** [comment]
I feel stupid.

Спасибо

**Comment by birdydma** [comment]
Random failures of engines flying in the shared cockpit is now fixed.
[smartcopilot.zip](https://github.com/mixMugz/An-24/files/5541393/smartcopilot.zip)

**Comment by mixMugz** [comment]
> Random failures of engines flying in the shared cockpit is now fixed.
> [smartcopilot.zip](https://github.com/mixMugz/An-24/files/5541393/smartcopilot.zip)

Thanks!
