### ISSUE TITLE
Почему не сделать корневую папку репозитория папкой модели?

### ISSUE THREAD

**Issue by julik** [mixMugz/An-24#4]
В исходном варианте (до Коли) корневая папка была собственно папкой самолета. Это удобно, потому что можно иметь живой git clone внутри папки Aircraft. То, как сделано сейчас, неудобно - хотя бы потому что в таком раскладе ни одного другого самолета который под контролем гита в копии X-Plane иметь нельзя. Будет ли XP загружать по symlink (или как это в windows называется) я не знаю, будет ли загружать SASL тоже.

Если я понимаю правильно сделано это было чтобы иметь под контролем версий папку с навдатой KLN - но KLN то можно и поменять? а загрузку навдаты сделать опциональной.

**Comment by mixMugz** [comment]
В этом нет необходимости. Учитывая что это скорее для разработки.
Для самолёта скоро будет возможность иметь крайнюю версию посредством плагина skunkcrafts_updater. Он будет обновлять прям в X-Plane
