### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by Oceanair15** [mixMugz/An-24#7]
Очень понравилась ваша работа! Даже более, чем...! 
Сейчас первый полёт.
1. Смущает при запуске двигателей остановка оборотов на 45%, снижение до 40%, зависание около 5-7 секунд, потом рост и норма.
2. Конфликт с файлом "tu154_paxi_gr.lua"
3. Звук радует: меняется в зависимости от режима, места в самолёте и правильно изменяется на пролёте Shift+2. А вот по Shft+4 при круговом обзоре он постоянный - это неверно.

**Comment by mixMugz** [comment]
1. Я по правде не знаю как должно быть. Если распишите логику работы - буду вам признателен за вклад. Логика работы в этом аспекте я не перерабатывал. Ну и если видосик покажете - буду признателен.
2. Какого плана конфликт? У нас нет такого файла в сборке. Что именно конфликтует?
3. Со звуком предстоит еще очень большая работа, и мне пока это с трудом даётся, из-за недостатка опыта. Но я думаю и это поправимо. 

Спасибо за отзыв.

**Comment by Oceanair15** [comment]
1. Ахха, если бы я знал! Видео запишу. Жаль, что у вас не сложилось с Троновым. Там Валера Рулёв это дефект исправил.
2. Это файл сообщений бортпроводников из папки скриптов и работает с Ту-154 Фелиса. В Ан-24 он вызывает "lua stopped" :-(

**Comment by mixMugz** [comment]
1. Ну мне тоже жаль. Некоторые люди не могут без драм
2. Но у нас не ту-154. Как он должен работать? У нас изменились датарефы, поэтому если есть полный пак - давайте попробую его оживить? С другим Ан-24 каким он работает?

**Comment by Oceanair15** [comment]
На другой Ан-24 этот файл не влияет. Какой пак нужен?

**Comment by Oceanair15** [comment]
2. С другими версиями этот файл не конфликтует. Он только для Ту-154. Но вот с вашей сборкой пока не дружит. Хотя никакого отношения к ней не имеет! Посмотрите, может чего откопаете.

[tu154_paxi_gr.zip](https://github.com/mixMugz/An-24/files/5065254/tu154_paxi_gr.zip)

**Comment by mixMugz** [comment]
Немного не понял. Где эти файлы должны лежать?

**Comment by mixMugz** [comment]
Ааа это для FlyWithLua?

**Comment by mixMugz** [comment]
Вот вам исправленный файл. Больше не будет ни с кем конфликтовать.
[tu154_paxi_gr.zip](https://github.com/mixMugz/An-24/files/5065545/tu154_paxi_gr.zip)

**Comment by Oceanair15** [comment]
По первому вопросу

**Comment by Oceanair15** [comment]
К первому вопросу:
[an-24rv_RPM.zip](https://github.com/mixMugz/An-24/files/5065848/an-24rv_RPM.zip)

**Comment by Oceanair15** [comment]
> Вот вам исправленный файл. Больше не будет ни с кем конфликтовать.
> [tu154_paxi_gr.zip](https://github.com/mixMugz/An-24/files/5065545/tu154_paxi_gr.zip)

Спасибо!
