### ISSUE TITLE
КППМ

### ISSUE THREAD

**Issue by Oceanair15** [mixMugz/An-24#8]
При установке курса на КППМ шкала сначала вращается медленно (привычно), потом резко ускоряется.

**Comment by mixMugz** [comment]
Это не бага, это фича. Если держать зажатым больше 6 секунд - то перемещение ускоряется. Сделано так специально, чтоб можно быстрее выйти на нужный курс. Тоже самое сделано в ГК52. Для точной подстройки можно использовать колёсико мышки, держа курсор над ручкой.

**Comment by mixMugz** [comment]
Могу закрывать issue?

**Comment by Oceanair15** [comment]
Да.
